global:
  hosts:
    domain: gitlab.local
    https: false
    externalIP: 192.168.56.110
  initialRootPassword: "gitlabadmin"
  kubernetes:
    enabled: true
    inCluster: true
  email: admin@gitlab.local
  certmanager-issuer:
    email: admin@gitlab.local

# Disable cert-manager completely
certmanager:
  install: false
  installCRDs: false

certmanager-issuer:
  email: admin@gitlab.local

# Disable NGINX ingress as we're using Traefik
nginx-ingress:
  enabled: false

gitlab-runner:
  install: true
  runners:
    config: |
      [[runners]]
        [runners.kubernetes]
        image = "ubuntu:20.04"

# Storage configurations
postgresql:
  persistence:
    size: 8Gi

redis:
  persistence:
    size: 5Gi

minio:
  persistence:
    size: 10Gi

# Component scaling
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    ingress:
      enabled: true #//!emain error
      tls:
        enabled: false #//!emain error
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1

# Disable SSL/TLS for development //!emain error
gitlab:
  webservice:
    ingress:
      tls:
        enabled: false
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    service:
      type: ClusterIP
      externalTrafficPolicy: Cluster

# Registry configuration
registry:
  enabled: true
  tls:
    enabled: false