global:
  hosts:
    domain: gitlab.local
    https: false
    externalIP: 192.168.56.110
  initialRootPassword:
    secret: gitlab-root-password
    key: password
  kubernetes:
    enabled: true
    inCluster: true
  email:
    from: gitlab@gitlab.local
    display_name: GitLab
    reply_to: noreply@gitlab.local

# Disable cert-manager
certmanager:
  install: false
  installCRDs: false

# Disable NGINX ingress as we're using Traefik
nginx-ingress:
  enabled: false

# Basic GitLab configuration
gitlab:
  webservice:
    ingress:
      enabled: true
      tls:
        enabled: false