global:
  hosts:
    domain: gitlab.local
    https: false
    externalIP: 192.168.56.110    # VM's IP address
  initialRootPassword: "gitlabadmin"
  # Enable Kubernetes integration
  kubernetes:
    enabled: true
    inCluster: true    # GitLab runs inside the cluster

certmanager:
  install: false    # Skip cert-manager installation

nginx-ingress:
  enabled: false    # Using existing ingress controller

gitlab-runner:
  install: true     # Install GitLab CI runner
  runners:
    config: |
      [[runners]]
        [runners.kubernetes]
        image = "ubuntu:20.04"    # Base image for CI jobs

# Configure storage for GitLab components
postgresql:
  persistence:
    size: 8Gi    # Database storage

redis:
  persistence:
    size: 5Gi    # Cache storage

minio:
  persistence:
    size: 10Gi   # Object storage

# Configure GitLab component scaling
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1