global:
  hosts:
    domain: gitlab.local
    https: false
    externalIP: 192.168.56.110
  initialRootPassword:
    secret: gitlab-root-password
    key: password
  kubernetes:
    enabled: true
    inCluster: true
  email:
    from: gitlab@gitlab.local
    display_name: GitLab
    reply_to: noreply@gitlab.local

# Disable cert-manager
certmanager:
  install: false
  installCRDs: false

# Add certmanager-issuer configuration
certmanager-issuer:
  email: gitlab@gitlab.local

# Disable NGINX ingress as we're using Traefik
nginx-ingress:
  enabled: false

# Basic GitLab configuration
gitlab:
  webservice:
    ingress:
      enabled: true
      tls:
        enabled: false
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 800Mi
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 200Mi

# Disable storage
postgresql:
  persistence:
    size: 2Gi
redis:
  persistence:
    size: 2Gi
minio:
  persistence:
    size: 5Gi