# Create a service account for GitLab to interact with Kubernetes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
  namespace: gitlab
---
# Grant cluster-admin permissions to the GitLab service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin    # Gives full cluster access to GitLab
subjects:
- kind: ServiceAccount
  name: gitlab-admin
  namespace: gitlab 