global:
  hosts:
    domain: gitlab.local
    https: false
    externalIP: 192.168.56.110
  initialRootPassword:
    secret: gitlab-root-password
    key: password

certmanager:
  install: false
  installCRDs: false

nginx-ingress:
  enabled: false

postgresql:
  persistence:
    size: 1Gi
redis:
  persistence:
    size: 1Gi
minio:
  persistence:
    size: 2Gi

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1