Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/alpine-3.20"

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = 1024
    virtualbox.cpus = 1
  end

  config.vm.define "mel-hadaS" do |server|
  server.vm.hostname = "mel-hadaS"
  server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder ".", "/vagrant"
    server.vm.provision "shell", privileged: true, path: "scripts/server.sh"
  end

  config.vm.define "mel-hadaSW" do |worker|
    worker.vm.hostname = "mel-hadaSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.synced_folder ".", "/vagrant"
    worker.vm.provision "shell", privileged: true, path: "scripts/worker.sh"
  end
end