# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use Ubuntu 22.04 (Jammy) as base image
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.define "gitlab" do |gitlab|
    # Set hostname for the VM
    gitlab.vm.hostname = "gitlab"
    # Configure private network with static IP
    gitlab.vm.network "private_network", ip: "192.168.56.110"
    
    # Configure VirtualBox provider settings
    gitlab.vm.provider "virtualbox" do |vb|
      # GitLab requires significant resources
      vb.memory = 8192  # Allocate 8GB RAM
      vb.cpus = 4       # Allocate 4 CPU cores
      
      # Disable USB
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end

    # Configure synced folder with proper permissions
    config.vm.synced_folder ".", "/vagrant", 
      owner: "vagrant",
      group: "vagrant",
      mount_options: ["dmode=775,fmode=664"]

    # Run the setup script after VM creation
    gitlab.vm.provision "shell", inline: <<-SHELL
      # Fix permissions for private key
      chmod 0600 /vagrant/.vagrant/machines/gitlab/virtualbox/private_key
    SHELL

    # Run the main setup script
    gitlab.vm.provision "shell", path: "scripts/setup.sh"
  end
end
